trigger:
- master

pool:
  name: 'Hosted Ubuntu 1604'

steps:
- bash: |
    sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo sudo dpkg -i google-chrome-stable_current_amd64.deb


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

